name: Generate Report

on:
  workflow_dispatch:
  push:
    paths:
      - data.yml
      - generate_report.py

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate report (local action)
        uses: ./action


      - name: Commit REPORT.md if changed
        run: |
          if git status --porcelain | grep -q "REPORT.md"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add REPORT.md
            git commit -m "chore: auto-generate REPORT.md"
            git push
          else
            echo "No changes to commit"
          fi
